project_id = "wgbgnrzogqonndoeijju"

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.sitemap]
verify_jwt = false

[functions.optimize-seo]
verify_jwt = false